apiVersion: v1
kind: Service
metadata:
  labels: 
    app: ngnix
    app.kubernetes.io/instance: argocd
  name: ngnix
  namespace: defalut
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ngnix
  type: NodePort 
